### ISSUE TITLE
Замечания по лабораторной работе 6

### ISSUE THREAD

**Issue by volgatech-web-development** [ondrop/web-development#4]
Нужно поправить форматирование, смотри
https://docs.google.com/document/d/1Rfb0ol6OQZygOqNmT2Zc3oaDHCA04iVLs-fkX9Qy7TE/edit
Нужно поправить структуру, смотри
https://docs.google.com/document/d/1tMiSMoEMmOpkLxRq9prjFx3efv-cVMSR4r7AFpQ3dFM/edit

**Comment by ondrop** [comment]
Поправил.
Можете еще допроверить 3.4, 3.5, 5.1, 5.2.
